use core::sync::atomic::AtomicU32;

use alloc::vec::Vec;

use crate::arch::aarch64::gic::its::commands::{GITS_COMMAND_QUEUE, ITSCommand};
use crate::arch::aarch64::gic::{LPI_MANAGER, its};
use crate::arch::aarch64::pci;
use crate::drivers::interrupts::{IRQInfo, IntTrigger};
use crate::drivers::pci::msi::MSIXInfo;
use crate::info;
use crate::utils::locks::{Mutex, SpinLock};
use lazy_static::lazy_static;

static NEXT_LPI_IRQ: AtomicU32 = AtomicU32::new(0x2000);

lazy_static! {
    /// a list of device IDs that are already mapped
    static ref MAPPED_DEVICE_IDS: Mutex<Vec<u32>> = Mutex::new(Vec::new());
}

static INTERRUPT_CONTROLLER: SpinLock<Option<&'static dyn CPUInterruptController>> =
    SpinLock::new(None);

use hfdt_rs::{Cells, Node};
pub trait CPUInterruptController: Send + Sync {
    fn node(&self) -> &Node<'static>;
    fn enable_dev_irq(&self, specifier: Cells, group: IntGroup) -> Result<u32, &'static str>;
    fn send_eoi(&self, irq: u32, is_fiq: bool);
}

/// The interrupt group
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IntGroup {
    #[allow(unused)]
    /// Group 0, Typically used by FIQs
    Secure = 0,
    /// Group 1, Typically used by IRQs
    NonSecure = 1,
}

/// Describes an IRQ generated by a device.
pub struct DeviceIrq {
    number: u32,
    controller: &'static dyn CPUInterruptController,
}

impl DeviceIrq {
    pub fn irq(&self) -> u32 {
        self.number
    }

    pub fn send_eoi(&self, is_fiq: bool) {
        self.controller.send_eoi(self.number, is_fiq);
    }
}

/// Register an interrupt controller for use with [`register_device_irq`].
pub fn register_int_controller(controller: &'static dyn CPUInterruptController) {
    info!(
        "Registering interrupt controller: {}",
        controller.node().name()
    );
    *INTERRUPT_CONTROLLER.lock() = Some(controller);
}

/// Register a device specific IRQ associated with the given interrupt parent.
pub fn register_device_irq(
    interrupt_parent: &Node<'static>,
    specifier: Cells,
    group: IntGroup,
) -> Result<DeviceIrq, &'static str> {
    let controller = INTERRUPT_CONTROLLER
        .lock()
        .ok_or("No interrupt controller registered")?;
    assert_eq!(
        interrupt_parent,
        controller.node(),
        "TODO: Allow multiple interrupt controllers?"
    );
    let int_id = controller.enable_dev_irq(specifier, group)?;
    Ok(DeviceIrq {
        controller,
        number: int_id,
    })
}

fn register_msix(int_id: u32, msix: &MSIXInfo) {
    let device_id = msix.requester_id();
    let event_id = int_id;

    let mut mapped_device_ids = MAPPED_DEVICE_IDS.lock();

    // building commands
    let mut command_queue = GITS_COMMAND_QUEUE.lock();

    // map deviceID if it isn't already mapped
    if !mapped_device_ids.contains(&device_id) {
        let (itt_addr, _, itt_range) = its::allocate_itt();
        command_queue.add_command(ITSCommand::new_mapd(
            device_id as u32,
            itt_range,
            itt_addr.into_phys(),
            true,
        ));
        mapped_device_ids.push(device_id);
    }
    drop(mapped_device_ids);

    // enable LPI
    LPI_MANAGER.lock().enable(event_id);
    // map the LPI to the deviceID and collection 0 (should be mapped to processor 0 )
    command_queue.add_command(ITSCommand::new_mapi(device_id as u32, event_id, 0));
    // invalidate to make sure LPI is enabled
    command_queue.add_command(ITSCommand::new_inv(device_id as u32, event_id));
    // Syncs commands for Processor 0 to make sure all of the previous changes are applied
    command_queue.add_command(ITSCommand::sync());
    // waits for all commands to complete
    command_queue.poll();
}

pub unsafe fn register_irq_handler(info: &IRQInfo, _triggering: IntTrigger) -> u32 {
    match info {
        IRQInfo::MSIX(msix) => {
            let int_id = NEXT_LPI_IRQ.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
            register_msix(int_id, msix);
            int_id
        }
        IRQInfo::PCIInt {
            bus,
            device,
            function,
            interrupt_pin,
            interrupt_line,
        } => {
            _ = interrupt_line;
            let (intc, specifier) = pci::lookup_int_map(
                *bus as u32,
                *device as u32,
                *function as u32,
                *interrupt_pin as u32,
            )
            .expect("Failed to get the interrupt specifier from PCI mapping");

            crate::debug!(
                "{bus}:{device}:{function} INT#{interrupt_pin} => {:?}",
                specifier
            );

            let int = register_device_irq(&intc, specifier, IntGroup::NonSecure)
                .expect("failed to register device IRQ");
            int.send_eoi(false);
            int.irq()
        }
    }
}
