[package]
name = "majala"
version = "0.1.0"
edition = "2024"
description = "A program to read SafaOS's kernel logs"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
safa-api = { version = "0.3.1", features = ["std"] }
