//! Tests for the PMM interface.
//!
//! This module was generated by free ChatGPT which isn't only an AI it is also worse than claude in every way
//! it got a lot of these tests wrong and I had to manually fix them.
//!
//! but i was too lazy to manually write tests.

use crate::misc::PAGE_SIZE;

use super::*;

#[test_case]
fn allocate_and_deallocate_multiple_real_frames() {
    let (initial_free, initial_mapped) = super::REGION_ALLOCATOR
        .lock_no_irq(|alloc| (alloc.count_frames_expensive(), alloc.mapped_frames()));

    const COUNT: usize = 8;

    let base = super::allocate_frames(1, COUNT).expect("failed to allocate contiguous frames");

    assert_eq!(
        super::REGION_ALLOCATOR.lock_no_irq(|alloc| { alloc.mapped_frames() - initial_mapped }),
        COUNT
    );

    // Verify the physical frames are actually contiguous.
    for i in 0..COUNT {
        let expected = base.addr() + i * PAGE_SIZE;

        assert_eq!(
            Frame::containing(expected).addr(),
            base.addr() + i * PAGE_SIZE
        );
    }

    super::REGION_ALLOCATOR.lock_no_irq(|alloc| {
        assert_eq!(alloc.count_frames_expensive(), initial_free - COUNT);

        assert_eq!(alloc.mapped_frames() - initial_mapped, COUNT);

        // The list must still have valid boundaries.
        if let Some(head) = alloc.head {
            assert!(unsafe { head.as_ref().prev }.is_none());
        }

        if let Some(tail) = alloc.tail {
            assert!(unsafe { tail.as_ref().next }.is_none());
        }
    });

    // Return the whole contiguous allocation.
    unsafe { super::deallocate_frames(base, COUNT).unwrap() };

    super::REGION_ALLOCATOR.lock_no_irq(|alloc| {
        assert_eq!(alloc.mapped_frames(), initial_mapped);
        assert_eq!(alloc.count_frames_expensive(), initial_free);
    });
}

#[test_case]
fn allocate_single_frame_real_allocator() {
    let initial = super::REGION_ALLOCATOR
        .lock_no_irq(|alloc| (alloc.mapped_frames(), alloc.count_frames_expensive()));

    // Allocate several real frames through the public allocator API.
    let a = super::allocate_frame().expect("failed to allocate frame A");
    let b = super::allocate_frame().expect("failed to allocate frame B");
    let c = super::allocate_frame().expect("failed to allocate frame C");

    assert_ne!(a.addr(), b.addr());
    assert_ne!(a.addr(), c.addr());
    assert_ne!(b.addr(), c.addr());

    super::REGION_ALLOCATOR.lock_no_irq(|alloc| {
        assert_eq!(alloc.mapped_frames(), initial.0 + 3);
        assert_eq!(alloc.count_frames_expensive(), initial.1 - 3);

        assert!(alloc.head.is_some());
        assert!(alloc.tail.is_some());

        unsafe {
            assert!(alloc.head.unwrap().as_ref().prev.is_none());
            assert!(alloc.tail.unwrap().as_ref().next.is_none());
        }
    });

    // Return all three frames.
    unsafe {
        super::deallocate_frame(a).expect("Failed to deallocate a");
        super::deallocate_frame(b).unwrap();
        super::deallocate_frame(c).unwrap();
    }

    super::REGION_ALLOCATOR.lock_no_irq(|alloc| {
        assert_eq!(alloc.mapped_frames(), initial.0);
        assert_eq!(alloc.count_frames_expensive(), initial.1);

        assert!(alloc.head.is_some());
        assert!(alloc.tail.is_some());

        unsafe {
            assert!(alloc.head.unwrap().as_ref().prev.is_none());
            assert!(alloc.tail.unwrap().as_ref().next.is_none());
        }
    });
}
