//! Tests for the frame allocator
//!
//! This module was generated by free ChatGPT which isn't only an AI it is also worse than claude in every way
//! it got a lot of these tests wrong and I had to manually fix them.
//!
//! but i was too lazy to manually write tests.
use core::ptr::NonNull;

use super::*;

#[test_case]
fn bitmap_set_bits_exhaustive_ranges() {
    // Test every range in a small bitmap, both setting and clearing.
    //
    // This catches:
    // - single-bit errors
    // - byte-boundary errors
    // - multi-byte errors
    // - first/last-bit errors
    // - partial-byte mask errors

    const BITS: usize = 24;

    for start in 0..BITS {
        for count in 0..=(BITS - start) {
            let mut bitmap = [0u8; 3];

            let result =
                RegionListAllocator::bitmap_set_bits_inner(&mut bitmap, start, count, true);

            assert_eq!(
                result,
                Some(((start, start + count), (start / 8, (start + count) / 8),)),
                "unexpected result for start={start}, count={count}"
            );

            for bit in 0..BITS {
                let byte = bitmap[bit / 8];
                let mask = 1 << (7 - bit % 8);
                let actual = byte & mask != 0;
                let expected = bit >= start && bit < start + count;

                assert_eq!(
                    actual, expected,
                    "set mismatch: start={start}, count={count}, bit={bit}"
                );
            }

            // Clear exactly the same range again.
            RegionListAllocator::bitmap_set_bits_inner(&mut bitmap, start, count, false);

            assert_eq!(
                bitmap,
                [0, 0, 0],
                "clear mismatch: start={start}, count={count}"
            );
        }
    }
}

#[test_case]
fn bitmap_set_bits_out_of_bounds() {
    let mut bitmap = [0u8; 2];

    // Entire bitmap.
    RegionListAllocator::bitmap_set_bits_inner(&mut bitmap, 0, 16, true);

    assert_eq!(bitmap, [0xff, 0xff]);

    // Clear starting in the middle and extending beyond the bitmap.
    RegionListAllocator::bitmap_set_bits_inner(&mut bitmap, 5, usize::MAX, false);

    assert_eq!(bitmap, [0xf8, 0x00]);

    // Start exactly at the end.
    assert_eq!(
        RegionListAllocator::bitmap_set_bits_inner(&mut bitmap, 16, 1, true,),
        None
    );

    // Start beyond the end.
    assert_eq!(
        RegionListAllocator::bitmap_set_bits_inner(&mut bitmap, 17, 1, true,),
        None
    );
}

#[test_case]
fn bitmap_lookup_free_cases() {
    fn make_allocator(bitmap: NonNull<[u8]>) -> RegionListAllocator {
        RegionListAllocator {
            head: None,
            tail: None,
            bitmap: Some(bitmap),
            allocations: 0,
            usable_regions: 0,
            unusable_regions: 0,
        }
    }

    // Empty bitmap.
    {
        let mut bitmap = [0u8];
        let bitmap = NonNull::from_mut(&mut bitmap);
        let alloc = make_allocator(bitmap);

        assert_eq!(alloc.bitmap_lookup_free(1, 1), Some(0));
        assert_eq!(alloc.bitmap_lookup_free(1, 8), Some(0));
        assert_eq!(alloc.bitmap_lookup_free(1, 9), None);
        assert_eq!(alloc.bitmap_lookup_free(1, 0), None);
        assert_eq!(alloc.bitmap_lookup_free(0, 1), Some(0));
    }

    // First page occupied.
    {
        let mut bitmap = [0x80];
        let bitmap = NonNull::from_mut(&mut bitmap);
        let alloc = make_allocator(bitmap);

        assert_eq!(alloc.bitmap_lookup_free(1, 1), Some(1));
        assert_eq!(alloc.bitmap_lookup_free(1, 7), Some(1));
        assert_eq!(alloc.bitmap_lookup_free(1, 8), None);
    }

    // Two free ranges separated by used pages.
    {
        let mut bitmap = [0b1110_0011];
        let bitmap = NonNull::from_mut(&mut bitmap);
        let alloc = make_allocator(bitmap);

        assert_eq!(alloc.bitmap_lookup_free(1, 3), Some(3));
        assert_eq!(alloc.bitmap_lookup_free(1, 4), None);
    }

    // Alignment.
    {
        let mut bitmap = [0u8; 2];
        let mut bitmap = NonNull::from_mut(&mut bitmap);
        let alloc = make_allocator(bitmap);

        assert_eq!(alloc.bitmap_lookup_free(1, 1), Some(0));
        assert_eq!(alloc.bitmap_lookup_free(2, 1), Some(0));
        assert_eq!(alloc.bitmap_lookup_free(4, 1), Some(0));
        assert_eq!(alloc.bitmap_lookup_free(8, 1), Some(0));

        // Occupy page 0. The next 8-aligned position is 8.
        unsafe { bitmap.as_mut()[0] = 0x80 };

        assert_eq!(alloc.bitmap_lookup_free(8, 1), Some(8));
    }

    // Alignment after a used bit.
    {
        let mut bitmap = [0x80u8, 0x0u8];
        let bitmap = NonNull::from_mut(&mut bitmap);

        let alloc = make_allocator(bitmap);

        assert_eq!(alloc.bitmap_lookup_free(4, 1), Some(4));
        assert_eq!(alloc.bitmap_lookup_free(8, 1), Some(8));
    }

    // A free range exists, but not at the requested alignment.
    {
        let mut bitmap = [0xff, 0x00, 0x00];
        let bitmap = NonNull::from_mut(&mut bitmap);
        let alloc = make_allocator(bitmap);

        assert_eq!(alloc.bitmap_lookup_free(1, 1), Some(8));
        assert_eq!(alloc.bitmap_lookup_free(4, 1), Some(8));
        assert_eq!(alloc.bitmap_lookup_free(8, 1), Some(8));
        assert_eq!(alloc.bitmap_lookup_free(16, 1), Some(16));
    }

    // Search should continue after a failed candidate.
    {
        let mut bitmap = [0b0111_1111, 0b0000_0000];
        let bitmap = NonNull::from_mut(&mut bitmap);
        let alloc = make_allocator(bitmap);

        assert_eq!(alloc.bitmap_lookup_free(1, 1), Some(0));
        assert_eq!(alloc.bitmap_lookup_free(1, 8), Some(8));
        assert_eq!(alloc.bitmap_lookup_free(4, 4), Some(8));
    }
}

#[test_case]
fn bitmap_set_and_lookup_round_trip() {
    fn make_allocator(bitmap: &mut [u8]) -> RegionListAllocator {
        RegionListAllocator {
            head: None,
            tail: None,
            bitmap: Some(NonNull::from(bitmap)),
            allocations: 0,
            usable_regions: 0,
            unusable_regions: 0,
        }
    }

    let mut bitmap = [0u8; 4];
    let mut alloc = make_allocator(&mut bitmap);

    // Start completely free.
    for count in 1..=32 {
        assert_eq!(
            alloc.bitmap_lookup_free(1, count),
            Some(0),
            "failed for count={count}"
        );
    }

    // Occupy [0, 3].
    alloc.bitmap_set_bits(0, 4, true);

    assert_eq!(alloc.bitmap_lookup_free(1, 1), Some(4));
    assert_eq!(alloc.bitmap_lookup_free(1, 4), Some(4));
    assert_eq!(alloc.bitmap_lookup_free(1, 28), Some(4));
    assert_eq!(alloc.bitmap_lookup_free(1, 29), None);

    // Occupy [4, 7], creating a byte-aligned free region at 8.
    alloc.bitmap_set_bits(4, 4, true);

    assert_eq!(alloc.bitmap_lookup_free(1, 1), Some(8));
    assert_eq!(alloc.bitmap_lookup_free(4, 1), Some(8));
    assert_eq!(alloc.bitmap_lookup_free(8, 1), Some(8));
    assert_eq!(alloc.bitmap_lookup_free(8, 3), Some(8));

    // Free the first four pages again.
    alloc.bitmap_set_bits(0, 4, false);

    assert_eq!(alloc.bitmap_lookup_free(1, 4), Some(0));
    assert_eq!(alloc.bitmap_lookup_free(2, 4), Some(0));
    assert_eq!(alloc.bitmap_lookup_free(4, 4), Some(0));
    assert_eq!(alloc.bitmap_lookup_free(8, 4), Some(0));
    assert_eq!(alloc.bitmap_lookup_free(8, 8), Some(8));
}

#[test_case]
fn mark_bitmap_used_cases() {
    let mut bitmap = [0u8; 4];

    // One page.
    RegionListAllocator::mark_bitmap_used(PhysAddr::new(0), PhysAddr::new(0), &mut bitmap, true);

    assert_eq!(bitmap[0], 0x80);

    // Three pages.
    RegionListAllocator::mark_bitmap_used(
        PhysAddr::new(PAGE_SIZE),
        PhysAddr::new(PAGE_SIZE * 3),
        &mut bitmap,
        true,
    );

    assert_eq!(bitmap[0], 0xf0);

    // Cross a byte boundary.
    RegionListAllocator::mark_bitmap_used(
        PhysAddr::new(PAGE_SIZE * 7),
        PhysAddr::new(PAGE_SIZE * 9),
        &mut bitmap,
        true,
    );

    assert_eq!(bitmap[0], 0xf1);
    assert_eq!(bitmap[1], 0xc0);

    // Re-marking an already used range must be harmless.
    let old = bitmap;

    RegionListAllocator::mark_bitmap_used(
        PhysAddr::new(PAGE_SIZE),
        PhysAddr::new(PAGE_SIZE * 3),
        &mut bitmap,
        true,
    );

    assert_eq!(bitmap, old);
}
