[build]
target = "x86_64-unknown-none"
[unstable]
bindeps = true
[target.x86_64-unknown-none]
rustflags = ["-C", "relocation-model=static"]
[target.aarch64-unknown-none]
rustflags = ["-C", "relocation-model=static"]
