name: Build and Test X86_64

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v1
      with:
        version: 0.13.0
    - name: Install deps
      run: sudo apt update -y && sudo apt install xorriso qemu-system -y
    - name: Setup
      run: rustup update && rustup target add x86_64-unknown-none
    - name: Build
      run: cd kernel && cargo build --verbose
    - name: ls
      run: pwd && ls
    - name: Run tests
      run: ./test.sh
    - uses: actions/upload-artifact@v4
      with:
        name: x86_64-iso
        path: safaos.iso
        if-no-files-found: error
