name: Build and Test X86_64

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - name: Install deps
        run: sudo apt update -y && sudo apt install xorriso qemu-system -y
      - name: Setup
        run: rustup update && rustup install nightly && rustup +nightly target add x86_64-unknown-none && rustup target add x86_64-unknown-none
      - name: Build
        run: cargo run init && cargo run build -v
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-iso
          path: out/safaos.iso
          if-no-files-found: error
      - name: ls
        run: pwd && ls
      - name: Run tests
        run: cargo run -- test --no-kvm --no-gui
      # TODO: add building tests
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-tests-iso
          path: out/safaos-tests.iso
          if-no-files-found: error
